# Generated by Django 3.2.8 on 2021-11-29 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('file', models.ImageField(height_field='alto', upload_to='imagenes/%Y/%m/%d/', verbose_name='imagen', width_field='ancho')),
                ('ancho', models.IntegerField(default=0, editable=False)),
                ('alto', models.IntegerField(default=0, editable=False)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Fecha de subida')),
                ('subida_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subida por usuario')),
            ],
        ),
    ]
