# Generated by Django 3.2.8 on 2021-12-08 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagen',
            options={'verbose_name': 'imagen', 'verbose_name_plural': 'imagenes'},
        ),
    ]
